const palette = {
  primary: '#E53535',
  primaryPressed: '#C42B2B',
  primarySoftLight: 'rgba(229, 53, 53, 0.12)',
  primarySoftDark: 'rgba(229, 53, 53, 0.18)',
  success: '#16A34A',
  successSoftLight: 'rgba(22, 163, 74, 0.14)',
  successSoftDark: 'rgba(22, 163, 74, 0.18)',
  accentLight: '#F6E6C7',
  accentDark: '#362916',
  accentSoftLight: '#FBF2E1',
  accentSoftDark: 'rgba(246, 230, 199, 0.1)',
  backgroundLight: '#F7F7F5',
  backgroundDark: '#0D0D0D',
  surfaceLight: '#FFFFFF',
  surfaceDark: '#171717',
  surfaceAltLight: '#F2F2F0',
  surfaceAltDark: '#232323',
  surfaceMutedLight: '#E8E8E4',
  surfaceMutedDark: '#2E2E2E',
  borderLight: '#EAEAE6',
  borderDark: '#2C2C2C',
  borderStrongLight: '#DDDCD5',
  borderStrongDark: '#3A3A3A',
  textLight: '#111111',
  textDark: '#F0F0EE',
  textSoftLight: '#666666',
  textSoftDark: '#9C9C9A',
  textMutedLight: '#9B9A94',
  textMutedDark: '#686866',
  shadowLight: 'rgba(17, 17, 17, 0.08)',
  shadowDark: 'rgba(0, 0, 0, 0.42)',
} as const;

export function buildAppTheme(dark: boolean) {
  return {
    dark,
    background: dark ? palette.backgroundDark : palette.backgroundLight,
    surface: dark ? palette.surfaceDark : palette.surfaceLight,
    surfaceAlt: dark ? palette.surfaceAltDark : palette.surfaceAltLight,
    surfaceMuted: dark ? palette.surfaceMutedDark : palette.surfaceMutedLight,
    border: dark ? palette.borderDark : palette.borderLight,
    borderStrong: dark ? palette.borderStrongDark : palette.borderStrongLight,
    text: dark ? palette.textDark : palette.textLight,
    textSoft: dark ? palette.textSoftDark : palette.textSoftLight,
    textMuted: dark ? palette.textMutedDark : palette.textMutedLight,
    primary: palette.primary,
    primaryPressed: palette.primaryPressed,
    primarySoft: dark ? palette.primarySoftDark : palette.primarySoftLight,
    success: palette.success,
    successSoft: dark ? palette.successSoftDark : palette.successSoftLight,
    accent: dark ? palette.accentDark : palette.accentLight,
    accentSoft: dark ? palette.accentSoftDark : palette.accentSoftLight,
    shadow: dark ? palette.shadowDark : palette.shadowLight,
  };
}

export type AppTheme = ReturnType<typeof buildAppTheme>;

export const semanticColors = {
  light: {
    background: palette.backgroundLight,
    foreground: palette.textLight,
    primary: palette.primary,
    muted: palette.textSoftLight,
    border: palette.borderLight,
    destructive: palette.primary,
  },
  dark: {
    background: palette.backgroundDark,
    foreground: palette.textDark,
    primary: palette.primary,
    muted: palette.textSoftDark,
    border: palette.borderDark,
    destructive: palette.primary,
  },
} as const;
